[package]
name = "reth-pure-tx-pool"
version = "0.1.0"
edition = "2024"

[dependencies]
reth-ethereum = { git = "https://github.com/paradigmxyz/reth.git", features = ["full", "test-utils"] }
eyre = "0.6"
tokio = { version = "1.44.2", default-features = false }